#!/bin/bash
echo "pre-commit"
BRANCH=$(git rev-parse --abbrev-ref HEAD)
FORBIDDENBRANCH=dev

file=".git/MERGE_MSG"
if [ -f "$file" ]
then
	MERGEBRANCH=$(<.git/MERGE_MSG)
	echo "This is merge branch $MERGEBRANCH"
fi

if [ "${BRANCH}" == "master" -a "${GIT_COMMIT_TO_MASTER}" != "true" ]
then
	if [[ $MERGEBRANCH == *$FORBIDDENBRANCH* ]]; then
		git reset --merge
		echo "All conditions statisfied."
		exit 1
	fi
fi
